// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Terradue.Metadata.EarthObservation,Ogc.Gco</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.ServiceModel.W3c.Xlink;
using Terradue.ServiceModel.Ogc.Gml321;
using Terradue.ServiceModel.Ogc.Gmd;


namespace Terradue.ServiceModel.Ogc.Gco {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_DataSet_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractDS_Aggregate_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_Initiative_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_Series_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_ProductionSeries_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_Sensor_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_Platform_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_OtherAggregate_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_StereoMate_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Metadata_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PT_Locale_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_Scope_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_DataQuality_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LI_Lineage_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LI_Source_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LI_ProcessStep_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DS_Association_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_RepresentativeFraction_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_AggregateInformation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Usage_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Keywords_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_BrowseGraphic_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractMD_Identification_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_ServiceIdentification_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_DataIdentification_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_MaintenanceInformation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Distribution_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Format_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Distributor_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_StandardOrderProcess_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_DigitalTransferOptions_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Medium_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Constraints_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_SecurityConstraints_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_LegalConstraints_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_PortrayalCatalogueReference_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_ApplicationSchemaInformation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_RangeDimension_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Band_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractMD_ContentInformation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_CoverageDescription_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_ImageDescription_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_FeatureCatalogueDescription_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_MetadataExtensionInformation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_ExtendedElementInformation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_GeometricObjects_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Dimension_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractMD_SpatialRepresentation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_VectorSpatialRepresentation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_GridSpatialRepresentation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Georectified_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Georeferenceable_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractRS_ReferenceSystem_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_ReferenceSystem_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractDQ_Result_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_QuantitativeResult_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_ConformanceResult_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractDQ_Element_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractDQ_Completeness_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_CompletenessCommission_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_CompletenessOmission_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractDQ_LogicalConsistency_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_ConceptualConsistency_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_DomainConsistency_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_FormatConsistency_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_TopologicalConsistency_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractDQ_PositionalAccuracy_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_AbsoluteExternalPositionalAccuracy_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_GriddedDataPositionalAccuracy_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_RelativeInternalPositionalAccuracy_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractDQ_ThematicAccuracy_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_ThematicClassificationCorrectness_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_NonQuantitativeAttributeAccuracy_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_QuantitativeAttributeAccuracy_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractDQ_TemporalAccuracy_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_AccuracyOfATimeMeasurement_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_TemporalConsistency_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DQ_TemporalValidity_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EX_VerticalExtent_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CI_Series_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CI_OnlineResource_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CI_Address_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CI_Telephone_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CI_Contact_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CI_ResponsibleParty_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CI_Date_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CI_Citation_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MD_Identifier_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RS_Identifier_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractEX_GeographicExtent_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EX_GeographicDescription_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EX_GeographicBoundingBox_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EX_BoundingPolygon_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EX_Extent_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EX_TemporalExtent_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EX_SpatialTemporalExtent_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiplicityRange_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Multiplicity_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MemberName_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PT_FreeText_Type))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TypeName_Type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute("AbstractObject", Namespace="http://www.isotc211.org/2005/gco", IsNullable=false)]
    public abstract partial class AbstractObject_Type {

        private string idField;

        private string uuidField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PT_FreeText_PropertyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class CharacterString_PropertyType {

        private string characterStringField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public string CharacterString {
            get {
                return this.characterStringField;
            }
            set {
                this.characterStringField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LocalisedCharacterString_PropertyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class ObjectReference_PropertyType {

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class CodeListValue_Type {

        private string codeListField;

        private string codeListValueField;

        private string codeSpaceField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string codeList {
            get {
                return this.codeListField;
            }
            set {
                this.codeListField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string codeListValue {
            get {
                return this.codeListValueField;
            }
            set {
                this.codeListValueField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string codeSpace {
            get {
                return this.codeSpaceField;
            }
            set {
                this.codeSpaceField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Date_PropertyType {

        private object itemField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("Date", typeof(string), IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(System.DateTime))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Integer_PropertyType {

        private string integerField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Integer {
            get {
                return this.integerField;
            }
            set {
                this.integerField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Measure_PropertyType {

        private MeasureType itemField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("Angle", typeof(AngleType))]
        [System.Xml.Serialization.XmlElementAttribute("Length", typeof(LengthType))]
        [System.Xml.Serialization.XmlElementAttribute("Measure", typeof(MeasureType))]
        [System.Xml.Serialization.XmlElementAttribute("Scale", typeof(ScaleType))]
        public MeasureType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Boolean_PropertyType {

        private bool booleanField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public bool Boolean {
            get {
                return this.booleanField;
            }
            set {
                this.booleanField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Decimal_PropertyType {

        private decimal decimalField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public decimal Decimal {
            get {
                return this.decimalField;
            }
            set {
                this.decimalField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Real_PropertyType {

        private double realField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public double Real {
            get {
                return this.realField;
            }
            set {
                this.realField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class DateTime_PropertyType {

        private System.DateTime dateTimeField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class RecordType_PropertyType {

        private RecordType_Type recordTypeField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public RecordType_Type RecordType {
            get {
                return this.recordTypeField;
            }
            set {
                this.recordTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute("RecordType", Namespace="http://www.isotc211.org/2005/gco", IsNullable=false)]
    public partial class RecordType_Type {

        private Terradue.ServiceModel.W3c.Xlink.typeType typeField;

        private bool typeFieldSpecified;

        private string hrefField;

        private string roleField;

        private string arcroleField;

        private string titleField;

        private Terradue.ServiceModel.W3c.Xlink.showType showField;

        private bool showFieldSpecified;

        private Terradue.ServiceModel.W3c.Xlink.actuateType actuateField;

        private bool actuateFieldSpecified;

        private string valueField;

        public RecordType_Type() {
            this.typeField = Terradue.ServiceModel.W3c.Xlink.typeType.simple;
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        public Terradue.ServiceModel.W3c.Xlink.typeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string arcrole {
            get {
                return this.arcroleField;
            }
            set {
                this.arcroleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        public Terradue.ServiceModel.W3c.Xlink.showType show {
            get {
                return this.showField;
            }
            set {
                this.showField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showSpecified {
            get {
                return this.showFieldSpecified;
            }
            set {
                this.showFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        public Terradue.ServiceModel.W3c.Xlink.actuateType actuate {
            get {
                return this.actuateField;
            }
            set {
                this.actuateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actuateSpecified {
            get {
                return this.actuateFieldSpecified;
            }
            set {
                this.actuateFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UnitOfMeasure_PropertyType {

        private UnitDefinitionType itemField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("BaseUnit", typeof(BaseUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("ConventionalUnit", typeof(ConventionalUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("DerivedUnit", typeof(DerivedUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("UnitDefinition", typeof(UnitDefinitionType), Namespace="http://www.opengis.net/gml/3.2")]
        public UnitDefinitionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Record_PropertyType {

        private object recordField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public object Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Distance_PropertyType {

        private LengthType distanceField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public LengthType Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UomLength_PropertyType {

        private UnitDefinitionType itemField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("BaseUnit", typeof(BaseUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("ConventionalUnit", typeof(ConventionalUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("DerivedUnit", typeof(DerivedUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("UnitDefinition", typeof(UnitDefinitionType), Namespace="http://www.opengis.net/gml/3.2")]
        public UnitDefinitionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class MemberName_PropertyType {

        private MemberName_Type memberNameField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public MemberName_Type MemberName {
            get {
                return this.memberNameField;
            }
            set {
                this.memberNameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute("MemberName", Namespace="http://www.isotc211.org/2005/gco", IsNullable=false)]
    public partial class MemberName_Type : AbstractObject_Type {

        private CharacterString_PropertyType aNameField;

        private TypeName_PropertyType attributeTypeField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public CharacterString_PropertyType aName {
            get {
                return this.aNameField;
            }
            set {
                this.aNameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        public TypeName_PropertyType attributeType {
            get {
                return this.attributeTypeField;
            }
            set {
                this.attributeTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class TypeName_PropertyType {

        private TypeName_Type typeNameField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public TypeName_Type TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute("TypeName", Namespace="http://www.isotc211.org/2005/gco", IsNullable=false)]
    public partial class TypeName_Type : AbstractObject_Type {

        private CharacterString_PropertyType aNameField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public CharacterString_PropertyType aName {
            get {
                return this.aNameField;
            }
            set {
                this.aNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class GenericName_PropertyType {

        private CodeType itemField;

        private ItemChoiceType10 itemElementNameField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("LocalName", typeof(CodeType))]
        [System.Xml.Serialization.XmlElementAttribute("ScopedName", typeof(CodeType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public CodeType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType10 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Binary_PropertyType {

        private Binary_Type binaryField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public Binary_Type Binary {
            get {
                return this.binaryField;
            }
            set {
                this.binaryField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute("Binary", Namespace="http://www.isotc211.org/2005/gco", IsNullable=false)]
    public partial class Binary_Type {

        private string srcField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/gml/3.2")]
    public partial class Boolean {

        private string nilReasonField;

        private bool valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Number_PropertyType {

        private object itemField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("Decimal", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("Integer", typeof(string), DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("Real", typeof(double))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UomVolume_PropertyType {

        private UnitDefinitionType itemField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("BaseUnit", typeof(BaseUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("ConventionalUnit", typeof(ConventionalUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("DerivedUnit", typeof(DerivedUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("UnitDefinition", typeof(UnitDefinitionType), Namespace="http://www.opengis.net/gml/3.2")]
        public UnitDefinitionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UomTime_PropertyType {

        private UnitDefinitionType itemField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("BaseUnit", typeof(BaseUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("ConventionalUnit", typeof(ConventionalUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("DerivedUnit", typeof(DerivedUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("UnitDefinition", typeof(UnitDefinitionType), Namespace="http://www.opengis.net/gml/3.2")]
        public UnitDefinitionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UomVelocity_PropertyType {

        private UnitDefinitionType itemField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("BaseUnit", typeof(BaseUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("ConventionalUnit", typeof(ConventionalUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("DerivedUnit", typeof(DerivedUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("UnitDefinition", typeof(UnitDefinitionType), Namespace="http://www.opengis.net/gml/3.2")]
        public UnitDefinitionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UomArea_PropertyType {

        private UnitDefinitionType itemField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("BaseUnit", typeof(BaseUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("ConventionalUnit", typeof(ConventionalUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("DerivedUnit", typeof(DerivedUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("UnitDefinition", typeof(UnitDefinitionType), Namespace="http://www.opengis.net/gml/3.2")]
        public UnitDefinitionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UomScale_PropertyType {

        private UnitDefinitionType itemField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("BaseUnit", typeof(BaseUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("ConventionalUnit", typeof(ConventionalUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("DerivedUnit", typeof(DerivedUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("UnitDefinition", typeof(UnitDefinitionType), Namespace="http://www.opengis.net/gml/3.2")]
        public UnitDefinitionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UomAngle_PropertyType {

        private UnitDefinitionType itemField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("BaseUnit", typeof(BaseUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("ConventionalUnit", typeof(ConventionalUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("DerivedUnit", typeof(DerivedUnitType), Namespace="http://www.opengis.net/gml/3.2")]
        [System.Xml.Serialization.XmlElementAttribute("UnitDefinition", typeof(UnitDefinitionType), Namespace="http://www.opengis.net/gml/3.2")]
        public UnitDefinitionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class ScopedName_PropertyType {

        private CodeType scopedNameField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public CodeType ScopedName {
            get {
                return this.scopedNameField;
            }
            set {
                this.scopedNameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class LocalName_PropertyType {

        private CodeType localNameField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public CodeType LocalName {
            get {
                return this.localNameField;
            }
            set {
                this.localNameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Scale_PropertyType {

        private ScaleType scaleField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public ScaleType Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Angle_PropertyType {

        private AngleType angleField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public AngleType Angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Length_PropertyType {

        private LengthType itemField;

        private ItemChoiceType9 itemElementNameField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute("Distance", typeof(LengthType))]
        [System.Xml.Serialization.XmlElementAttribute("Length", typeof(LengthType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public LengthType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType9 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class Multiplicity_PropertyType {

        private Multiplicity_Type multiplicityField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public Multiplicity_Type Multiplicity {
            get {
                return this.multiplicityField;
            }
            set {
                this.multiplicityField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute("Multiplicity", Namespace="http://www.isotc211.org/2005/gco", IsNullable=false)]
    public partial class Multiplicity_Type : AbstractObject_Type {

        private MultiplicityRange_PropertyType[] rangeField;

        [System.Xml.Serialization.XmlElementAttribute("range")]
        public MultiplicityRange_PropertyType[] range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class MultiplicityRange_PropertyType {

        private MultiplicityRange_Type multiplicityRangeField;

        private string uuidrefField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public MultiplicityRange_Type MultiplicityRange {
            get {
                return this.multiplicityRangeField;
            }
            set {
                this.multiplicityRangeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuidref {
            get {
                return this.uuidrefField;
            }
            set {
                this.uuidrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute("MultiplicityRange", Namespace="http://www.isotc211.org/2005/gco", IsNullable=false)]
    public partial class MultiplicityRange_Type : AbstractObject_Type {

        private Integer_PropertyType lowerField;

        private UnlimitedInteger_PropertyType upperField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public Integer_PropertyType lower {
            get {
                return this.lowerField;
            }
            set {
                this.lowerField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        public UnlimitedInteger_PropertyType upper {
            get {
                return this.upperField;
            }
            set {
                this.upperField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UnlimitedInteger_PropertyType {

        private UnlimitedInteger_Type unlimitedIntegerField;

        private string nilReasonField;

        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UnlimitedInteger_Type UnlimitedInteger {
            get {
                return this.unlimitedIntegerField;
            }
            set {
                this.unlimitedIntegerField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string nilReason {
            get {
                return this.nilReasonField;
            }
            set {
                this.nilReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco")]
    [System.Xml.Serialization.XmlRootAttribute("UnlimitedInteger", Namespace="http://www.isotc211.org/2005/gco", IsNullable=true)]
    public partial class UnlimitedInteger_Type {

        private bool isInfiniteField;

        private bool isInfiniteFieldSpecified;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isInfinite {
            get {
                return this.isInfiniteField;
            }
            set {
                this.isInfiniteField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isInfiniteSpecified {
            get {
                return this.isInfiniteFieldSpecified;
            }
            set {
                this.isInfiniteFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType="nonNegativeInteger")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco", IncludeInSchema=false)]
    public enum ItemChoiceType9 {

        /// <remarks/>
        Distance,

        /// <remarks/>
        Length,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.isotc211.org/2005/gco", IncludeInSchema=false)]
    public enum ItemChoiceType10 {

        /// <remarks/>
        LocalName,

        /// <remarks/>
        ScopedName,
    }
}
