// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Terradue.ServiceModel.Ogc.Lmb20</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.ServiceModel.Ogc.Eop21;
using Terradue.ServiceModel.Ogc.Om20;
using Terradue.ServiceModel.Ogc.Gml321;

namespace Terradue.ServiceModel.Ogc.Lmb21
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "EarthObservationType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("EarthObservation", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbEarthObservationType : EarthObservationType
    {


    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/eop/2.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/eop/2.1", IsNullable = true)]
    public partial class LmbEarthObservationEquipmentPropertyType : EarthObservationEquipmentPropertyType
    {


    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "FootprintType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Footprint", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbFootprintType : Terradue.ServiceModel.Ogc.Alt21.AltFootprintType
    {

        private MeasureType maximumAltitudeField;

        private MeasureType minimumAltitudeField;

        private MultiPointPropertyType occultationPointsField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public MeasureType maximumAltitude
        {
            get
            {
                return this.maximumAltitudeField;
            }
            set
            {
                this.maximumAltitudeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        public MeasureType minimumAltitude
        {
            get
            {
                return this.minimumAltitudeField;
            }
            set
            {
                this.minimumAltitudeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        public MultiPointPropertyType occultationPoints
        {
            get
            {
                return this.occultationPointsField;
            }
            set
            {
                this.occultationPointsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "SensorType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Sensor", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbSensorType : SensorType
    {

        private MeasurementTypeValueType measurementTypeField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public MeasurementTypeValueType measurementType
        {
            get
            {
                return this.measurementTypeField;
            }
            set
            {
                this.measurementTypeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/lmb/2.1")]
    public enum MeasurementTypeValueType {

        /// <remarks/>
        EMISSION,

        /// <remarks/>
        ABSORPTION,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AcquisitionType", Namespace = "http://www.opengis.net/lmb/2.1")]
    [System.Xml.Serialization.XmlRootAttribute("Acquisition", Namespace = "http://www.opengis.net/lmb/2.1", IsNullable = false)]
    public partial class LmbAcquisitionType : AcquisitionType
    {

        private string observationModeField;

        private MeasureType verticalResolutionField;

        [System.Xml.Serialization.XmlElementAttribute()]
        public string observationMode
        {
            get
            {
                return this.observationModeField;
            }
            set
            {
                this.observationModeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        public MeasureType verticalResolution
        {
            get
            {
                return this.verticalResolutionField;
            }
            set
            {
                this.verticalResolutionField = value;
            }
        }
    }

}