// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Terradue.ServiceModel.W3c.Smil20Lang</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using Terradue.ServiceModel.W3c.Smil20;


namespace Terradue.ServiceModel.W3c.Smil20Lang
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    [System.Xml.Serialization.XmlRootAttribute("animate", Namespace = "http://www.w3.org/2001/SMIL20/Language", IsNullable = false)]
    public partial class animateType : animatePrototype
    {

        private System.Xml.XmlElement[] itemsField;

        private string targetElementField;

        private animateTypeCalcMode calcModeField;

        private bool skipcontentField;

        private System.Xml.XmlAttribute[] anyAttrField;

        public animateType()
        {
            this.calcModeField = animateTypeCalcMode.linear;
            this.skipcontentField = true;
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string targetElement
        {
            get
            {
                return this.targetElementField;
            }
            set
            {
                this.targetElementField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(animateTypeCalcMode.linear)]
        public animateTypeCalcMode calcMode
        {
            get
            {
                return this.calcModeField;
            }
            set
            {
                this.calcModeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("skip-content")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool skipcontent
        {
            get
            {
                return this.skipcontentField;
            }
            set
            {
                this.skipcontentField = value;
            }
        }

        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    [System.Xml.Serialization.XmlRootAttribute("animateMotion", Namespace = "http://www.w3.org/2001/SMIL20/Language", IsNullable = false)]
    public partial class animateMotionType : animateMotionPrototype
    {

        private System.Xml.XmlElement[] itemsField;

        private string targetElementField;

        private animateTypeCalcMode calcModeField;

        private bool skipcontentField;

        private System.Xml.XmlAttribute[] anyAttrField;

        public animateMotionType()
        {
            this.calcModeField = animateTypeCalcMode.linear;
            this.skipcontentField = true;
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string targetElement
        {
            get
            {
                return this.targetElementField;
            }
            set
            {
                this.targetElementField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(animateTypeCalcMode.linear)]
        public animateTypeCalcMode calcMode
        {
            get
            {
                return this.calcModeField;
            }
            set
            {
                this.calcModeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("skip-content")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool skipcontent
        {
            get
            {
                return this.skipcontentField;
            }
            set
            {
                this.skipcontentField = value;
            }
        }

        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    [System.Xml.Serialization.XmlRootAttribute("animateColor", Namespace = "http://www.w3.org/2001/SMIL20/Language", IsNullable = false)]
    public partial class animateColorType : animateColorPrototype
    {

        private System.Xml.XmlElement[] itemsField;

        private string targetElementField;

        private animateTypeCalcMode calcModeField;

        private bool skipcontentField;

        private System.Xml.XmlAttribute[] anyAttrField;

        public animateColorType()
        {
            this.calcModeField = animateTypeCalcMode.linear;
            this.skipcontentField = true;
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string targetElement
        {
            get
            {
                return this.targetElementField;
            }
            set
            {
                this.targetElementField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(animateTypeCalcMode.linear)]
        public animateTypeCalcMode calcMode
        {
            get
            {
                return this.calcModeField;
            }
            set
            {
                this.calcModeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("skip-content")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool skipcontent
        {
            get
            {
                return this.skipcontentField;
            }
            set
            {
                this.skipcontentField = value;
            }
        }

        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2001/SMIL20/Language")]
    [System.Xml.Serialization.XmlRootAttribute("set", Namespace = "http://www.w3.org/2001/SMIL20/Language", IsNullable = false)]
    public partial class setType : setPrototype
    {

        private System.Xml.XmlElement[] itemsField;

        private string targetElementField;

        private bool skipcontentField;

        private System.Xml.XmlAttribute[] anyAttrField;

        public setType()
        {
            this.skipcontentField = true;
        }

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string targetElement
        {
            get
            {
                return this.targetElementField;
            }
            set
            {
                this.targetElementField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("skip-content")]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool skipcontent
        {
            get
            {
                return this.skipcontentField;
            }
            set
            {
                this.skipcontentField = value;
            }
        }

        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
}
